/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.TipoUsuario;
import gui.auxiliares.posicionamientoVentanas;
import static gui.auxiliares.posicionamientoVentanas.centrarVentana;

import java.awt.*;

import javax.swing.*;

/**
 *
 * @author alumnogreibd
 */
public final class VUsuario extends javax.swing.JFrame{

    /**
     * Creates new form VProfesor
     */
    aplicacion.FachadaAplicacion fa;
    
    public VUsuario(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
        posicionamientoVentanas.centrarVentana(this);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VAdmin = new javax.swing.JFrame();
        JPanelAdmin = new javax.swing.JPanel();
        comboSeleccionTipoUsuarioDesdeAdmin = new javax.swing.JComboBox<>();
        btnSalir1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        VProfesor = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        comboSeleccionTipoUsuarioDesdeProfesor = new javax.swing.JComboBox<>();
        btnSalir2 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSesionesProfesor = new javax.swing.JTable();
        labelNombre = new javax.swing.JLabel();
        labelAula = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JLabel();
        btnBorrar1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        JPanelCliente = new javax.swing.JPanel();
        comboSeleccionTipoUsuarioDesdeUsuario = new javax.swing.JComboBox<>();
        btnSalir = new java.awt.Button();
        txtNumeroGrupo = new javax.swing.JTextField();
        txtNombreAula = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        labelNGrupoCliente = new javax.swing.JLabel();
        labelAulaCliente = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        txtNumeroGrupo1 = new javax.swing.JTextField();
        labelProfesor = new javax.swing.JLabel();
        txtProfesor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSesionesCliente = new javax.swing.JTable();

        VAdmin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VAdmin.setTitle("Menú Principal");
        VAdmin.setMinimumSize(new java.awt.Dimension(100, 100));
        VAdmin.setName("lienzoPrincipal"); // NOI18N

        JPanelAdmin.setBackground(new java.awt.Color(53, 126, 199));
        JPanelAdmin.setPreferredSize(new java.awt.Dimension(600, 500));

        comboSeleccionTipoUsuarioDesdeAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Profesor", "Administrador" }));
        comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(2);
        comboSeleccionTipoUsuarioDesdeAdmin.setToolTipText("Selecciona que vista quieres usar");
        comboSeleccionTipoUsuarioDesdeAdmin.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuarioDesdeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioDesdeAdminActionPerformed(evt);
            }
        });

        btnSalir1.setActionCommand("btnSalir");
        btnSalir1.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir1.setLabel("Salir");
        btnSalir1.setName("btnAdminSalir"); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout JPanelAdminLayout = new javax.swing.GroupLayout(JPanelAdmin);
        JPanelAdmin.setLayout(JPanelAdminLayout);
        JPanelAdminLayout.setHorizontalGroup(
            JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAdminLayout.createSequentialGroup()
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAdminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelAdminLayout.createSequentialGroup()
                        .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelAdminLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboSeleccionTipoUsuarioDesdeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelAdminLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(146, 146, 146)
                                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JPanelAdminLayout.setVerticalGroup(
            JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuarioDesdeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSalir1.getAccessibleContext().setAccessibleDescription("Botón que sale de la apliación");

        javax.swing.GroupLayout VAdminLayout = new javax.swing.GroupLayout(VAdmin.getContentPane());
        VAdmin.getContentPane().setLayout(VAdminLayout);
        VAdminLayout.setHorizontalGroup(
            VAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VAdminLayout.setVerticalGroup(
            VAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelAdmin.getAccessibleContext().setAccessibleName("JPanel administrador");
        JPanelAdmin.getAccessibleContext().setAccessibleDescription("panel que contiene los componentes de las ventanas para administradores");

        centrarVentana(VAdmin);

        VProfesor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VProfesor.setTitle("Menú Principal");
        VProfesor.setMinimumSize(new java.awt.Dimension(100, 100));
        VProfesor.setName("lienzoPrincipal"); // NOI18N
        VProfesor.setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel3.setBackground(new java.awt.Color(53, 126, 199));
        jPanel3.setName(""); // NOI18N

        comboSeleccionTipoUsuarioDesdeProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Profesor", "Administrador" }));
        comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(1);
        comboSeleccionTipoUsuarioDesdeProfesor.setToolTipText("Seleccione que vista quiere ver");
        comboSeleccionTipoUsuarioDesdeProfesor.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuarioDesdeProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioDesdeProfesorActionPerformed(evt);
            }
        });

        btnSalir2.setActionCommand("btnSalir");
        btnSalir2.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir2.setLabel("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        tablaSesionesProfesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaSesionesProfesor);

        labelNombre.setText("Nombre:");

        labelAula.setText("Aula:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goma.png"))); // NOI18N
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });

        btnBorrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear.png"))); // NOI18N
        btnBorrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrar1MouseClicked(evt);
            }
        });

        jButton5.setText("Sesiones");

        jButton6.setText("Alumnos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(comboSeleccionTipoUsuarioDesdeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 474, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelNombre)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelAula)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton6))
                                .addGap(51, 51, 51)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBorrar1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuarioDesdeProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(labelAula)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5)
                                .addComponent(jButton6))))
                    .addComponent(btnBuscar)
                    .addComponent(btnBorrar)
                    .addComponent(btnBorrar1))
                .addContainerGap())
        );

        btnSalir2.getAccessibleContext().setAccessibleDescription("Permite salir de la aplicación");

        javax.swing.GroupLayout VProfesorLayout = new javax.swing.GroupLayout(VProfesor.getContentPane());
        VProfesor.getContentPane().setLayout(VProfesorLayout);
        VProfesorLayout.setHorizontalGroup(
            VProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VProfesorLayout.setVerticalGroup(
            VProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VProfesor.getAccessibleContext().setAccessibleParent(this);
        centrarVentana(VProfesor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMinimumSize(new java.awt.Dimension(100, 100));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("lienzoPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));

        JPanelCliente.setBackground(new java.awt.Color(53, 126, 199));

        comboSeleccionTipoUsuarioDesdeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Profesor", "Administrador" }));
        comboSeleccionTipoUsuarioDesdeUsuario.setToolTipText("Seleccione que vista desea ver");
        comboSeleccionTipoUsuarioDesdeUsuario.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuarioDesdeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setActionCommand("btnSalir");
        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtNumeroGrupo.setToolTipText("Número del grupo a buscar");
        txtNumeroGrupo.setActionCommand("<Not Set>");

        txtNombreAula.setToolTipText("Aula en la que se realiza la actividad");
        txtNombreAula.setName("txtAula"); // NOI18N

        jTextField3.setToolTipText("Introduce aquí la fecha a buscar");
        jTextField3.setName("txtFecha"); // NOI18N

        labelNGrupoCliente.setText("Nº de grupo");

        labelAulaCliente.setText("Aula");

        jLabelFecha.setText("Fecha");
        jLabelFecha.setName("jLabelFecha"); // NOI18N

        labelHora.setText("Hora");

        txtNumeroGrupo1.setToolTipText("Hora en la que se llevará a cabo la actividad");
        txtNumeroGrupo1.setActionCommand("<Not Set>");
        txtNumeroGrupo1.setName("txtHora"); // NOI18N

        labelProfesor.setText("Profesor");
        labelProfesor.setName("lblProfesor"); // NOI18N

        txtProfesor.setToolTipText("Profesor que dirige el grupo");
        txtProfesor.setActionCommand("<Not Set>");
        txtProfesor.setName("txtProfesor"); // NOI18N

        tablaSesionesCliente.setModel(new ModeloTablaSesionesClientes());
        jScrollPane1.setViewportView(tablaSesionesCliente);

        javax.swing.GroupLayout JPanelClienteLayout = new javax.swing.GroupLayout(JPanelCliente);
        JPanelCliente.setLayout(JPanelClienteLayout);
        JPanelClienteLayout.setHorizontalGroup(
            JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelClienteLayout.createSequentialGroup()
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelClienteLayout.createSequentialGroup()
                                .addComponent(comboSeleccionTipoUsuarioDesdeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNumeroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNGrupoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNumeroGrupo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelClienteLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(labelAulaCliente)
                                .addGap(41, 41, 41)
                                .addComponent(jLabelFecha))
                            .addGroup(JPanelClienteLayout.createSequentialGroup()
                                .addComponent(txtNombreAula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(209, 209, 209))
                    .addGroup(JPanelClienteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        JPanelClienteLayout.setVerticalGroup(
            JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboSeleccionTipoUsuarioDesdeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNGrupoCliente)
                        .addComponent(labelAulaCliente)
                        .addComponent(jLabelFecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHora)
                    .addComponent(labelProfesor))
                .addGap(4, 4, 4)
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroGrupo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        comboSeleccionTipoUsuarioDesdeUsuario.getAccessibleContext().setAccessibleName("desplegableTipoAcceso");
        comboSeleccionTipoUsuarioDesdeUsuario.getAccessibleContext().setAccessibleDescription("Permite escoger el tipo de acceso");
        btnSalir.getAccessibleContext().setAccessibleDescription("Sale de la aplicación");
        txtNumeroGrupo.getAccessibleContext().setAccessibleName("CampoBúsquedaGrupo");
        txtNombreAula.getAccessibleContext().setAccessibleName("CampoBúsquedaGrupo");
        txtNombreAula.getAccessibleContext().setAccessibleDescription("Número del grupo a buscar");
        jTextField3.getAccessibleContext().setAccessibleName("Entrada Fecha a buscar");
        labelAulaCliente.getAccessibleContext().setAccessibleDescription("Etiqueta en la que se lee \"Aula\". Debajo se puede insertar un nombre de aula para realizar una búsqueda");
        jLabelFecha.getAccessibleContext().setAccessibleDescription("Etiqueta en la que pone fecha. Se espera la fecha a buscar debajo");
        txtNumeroGrupo1.getAccessibleContext().setAccessibleName("HoraGrupoBuscar");
        txtNumeroGrupo1.getAccessibleContext().setAccessibleDescription("Campo para introducir la hora a buscar");
        labelProfesor.getAccessibleContext().setAccessibleDescription("");
        txtProfesor.getAccessibleContext().setAccessibleName("entradaProfesor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelCliente.getAccessibleContext().setAccessibleName("Panel Cliente");
        JPanelCliente.getAccessibleContext().setAccessibleDescription("Panel que contiene los componentes que verán los clientes");

        getAccessibleContext().setAccessibleDescription("Pantall del menú principal");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void seleccionarPantalla(JComboBox<String> comboBox)
    {
        switch(comboBox.getSelectedIndex()){
            case 0:
                this.setVisible(true);
                VAdmin.setVisible(false);
                VProfesor.setVisible(false);
                this.pack();
                comboBox.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(0);
                break;

            case 1:
                this.setVisible(false);
                VAdmin.setVisible(false);
                VProfesor.setVisible(true);
                VProfesor.pack();
                comboBox.setSelectedIndex(1);
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(1);
                comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(1);
                comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(1);
                break;

            case 2:
                this.setVisible(false);
                VAdmin.setVisible(true);
                VProfesor.setVisible(false);
                VAdmin.pack();
                comboBox.setSelectedIndex(2);
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(2);
                comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(2);
                comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(2);
                break;

        }
    }
    
    private void comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuarioDesdeUsuario);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed

    private void comboSeleccionTipoUsuarioDesdeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioDesdeAdminActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuarioDesdeAdmin);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioDesdeAdminActionPerformed

    private void comboSeleccionTipoUsuarioDesdeProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioDesdeProfesorActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuarioDesdeProfesor);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioDesdeProfesorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Ahora toca salir
        salidaEstandarUsuario();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        salidaEstandarUsuario();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        salidaEstandarUsuario();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnBorrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrar1MouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAdmin;
    private javax.swing.JPanel JPanelCliente;
    private javax.swing.JFrame VAdmin;
    private javax.swing.JFrame VProfesor;
    private javax.swing.JLabel btnBorrar;
    private javax.swing.JLabel btnBorrar1;
    private javax.swing.JLabel btnBuscar;
    private java.awt.Button btnSalir;
    private java.awt.Button btnSalir1;
    private java.awt.Button btnSalir2;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuarioDesdeAdmin;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuarioDesdeProfesor;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuarioDesdeUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel labelAula;
    private javax.swing.JLabel labelAulaCliente;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelNGrupoCliente;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelProfesor;
    private javax.swing.JTable tablaSesionesCliente;
    private javax.swing.JTable tablaSesionesProfesor;
    private javax.swing.JTextField txtNombreAula;
    private javax.swing.JTextField txtNumeroGrupo;
    private javax.swing.JTextField txtNumeroGrupo1;
    private javax.swing.JTextField txtProfesor;
    // End of variables declaration//GEN-END:variables

    public void actualizarNivelAcceso(TipoUsuario nivelAcceso)
    {
        switch(nivelAcceso)
        {
            case Cliente:
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeUsuario.setModel(new DefaultComboBoxModel<>(new String[] { "Cliente" }));
                comboSeleccionTipoUsuarioDesdeAdmin.setModel(new DefaultComboBoxModel<>(new String[] { "Cliente" }));
                comboSeleccionTipoUsuarioDesdeProfesor.setModel(new DefaultComboBoxModel<>(new String[] { "Cliente" }));
                break;
            case Administrador:
                // DO - NOTHING
                // No hay que hacer nada, ya que el administrador puede ver todas las opciones
                break;
            case Profesor:
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeUsuario.setModel(new DefaultComboBoxModel<>(new String[] {"Cliente", "Profesor" }));
                comboSeleccionTipoUsuarioDesdeProfesor.setModel(new DefaultComboBoxModel<>(new String[] {"Cliente", "Profesor" }));
                break;
        }
    }

    private void salidaEstandarUsuario() {
        this.dispose();
        System.out.println("INFO: Saliendo de la aplicación. Nada que reportar.");
        System.exit(0);
    }

}
