/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.*;

/**
 *
 * @author alumnogreibd
 */
public class VUsuario extends javax.swing.JFrame{

    /**
     * Creates new form VProfesor
     */
    aplicacion.FachadaAplicacion fa;
    
    public VUsuario(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VAdmin = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        comboSeleccionTipoUsuario1 = new javax.swing.JComboBox<>();
        btnSalir1 = new java.awt.Button();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        VProfesor = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        comboSeleccionTipoUsuario2 = new javax.swing.JComboBox<>();
        btnSalir2 = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        comboSeleccionTipoUsuario = new javax.swing.JComboBox<>();
        btnSalir = new java.awt.Button();

        VAdmin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VAdmin.setTitle("Menú Principal");
        VAdmin.setMinimumSize(new java.awt.Dimension(100, 100));
        VAdmin.setName("lienzoPrincipal"); // NOI18N
        VAdmin.setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBackground(new java.awt.Color(53, 126, 199));

        comboSeleccionTipoUsuario1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Administrador", "Profesor" }));
        comboSeleccionTipoUsuario1.setSelectedIndex(1);
        comboSeleccionTipoUsuario1.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuario1ActionPerformed(evt);
            }
        });

        btnSalir1.setActionCommand("btnSalir");
        btnSalir1.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir1.setLabel("button1");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboSeleccionTipoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 474, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VAdminLayout = new javax.swing.GroupLayout(VAdmin.getContentPane());
        VAdmin.getContentPane().setLayout(VAdminLayout);
        VAdminLayout.setHorizontalGroup(
            VAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VAdminLayout.setVerticalGroup(
            VAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VProfesor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VProfesor.setTitle("Menú Principal");
        VProfesor.setMinimumSize(new java.awt.Dimension(100, 100));
        VProfesor.setName("lienzoPrincipal"); // NOI18N
        VProfesor.setPreferredSize(new java.awt.Dimension(600, 500));
        VProfesor.setType(java.awt.Window.Type.UTILITY);

        jPanel3.setBackground(new java.awt.Color(53, 126, 199));

        comboSeleccionTipoUsuario2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Administrador", "Profesor" }));
        comboSeleccionTipoUsuario2.setSelectedIndex(2);
        comboSeleccionTipoUsuario2.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuario2ActionPerformed(evt);
            }
        });

        btnSalir2.setActionCommand("btnSalir");
        btnSalir2.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir2.setLabel("button1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboSeleccionTipoUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 474, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuario2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VProfesorLayout = new javax.swing.GroupLayout(VProfesor.getContentPane());
        VProfesor.getContentPane().setLayout(VProfesorLayout);
        VProfesorLayout.setHorizontalGroup(
            VProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VProfesorLayout.setVerticalGroup(
            VProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VProfesor.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMinimumSize(new java.awt.Dimension(100, 100));
        setName("lienzoPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(53, 126, 199));

        comboSeleccionTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Administrador", "Profesor" }));
        comboSeleccionTipoUsuario.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setActionCommand("btnSalir");
        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setLabel("button1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboSeleccionTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 474, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        comboSeleccionTipoUsuario.getAccessibleContext().setAccessibleName("desplegableTipoAcceso");
        comboSeleccionTipoUsuario.getAccessibleContext().setAccessibleDescription("Permite escoger el tipo de acceso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("Pantall del menú principal");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void seleccionarPantalla(JComboBox<String> comboBox)
    {
        switch(comboBox.getSelectedIndex()){
            case 0:
                this.setVisible(true);
                VAdmin.setVisible(false);
                VProfesor.setVisible(false);
                this.pack();
                comboSeleccionTipoUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuario1.setSelectedIndex(0);
                comboSeleccionTipoUsuario2.setSelectedIndex(0);
                break;
            case 1:
                this.setVisible(false);
                VAdmin.setVisible(true);
                VProfesor.setVisible(false);
                VAdmin.pack();
                comboBox.setSelectedIndex(1);
                comboSeleccionTipoUsuario1.setSelectedIndex(1);
                comboSeleccionTipoUsuario2.setSelectedIndex(1);
                break;
            case 2:
                this.setVisible(false);
                VAdmin.setVisible(false);
                VProfesor.setVisible(true);
                VProfesor.pack();
                comboSeleccionTipoUsuario.setSelectedIndex(2);
                comboSeleccionTipoUsuario1.setSelectedIndex(2);
                comboSeleccionTipoUsuario2.setSelectedIndex(2);
                break;
        }
    }
    
    private void comboSeleccionTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuario);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioActionPerformed

    private void comboSeleccionTipoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuario1ActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuario1);
    }//GEN-LAST:event_comboSeleccionTipoUsuario1ActionPerformed

    private void comboSeleccionTipoUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuario2ActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuario2);
    }//GEN-LAST:event_comboSeleccionTipoUsuario2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame VAdmin;
    private javax.swing.JFrame VProfesor;
    private java.awt.Button btnSalir;
    private java.awt.Button btnSalir1;
    private java.awt.Button btnSalir2;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuario;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuario1;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuario2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
